project_FlwUpSys/Dashboard/urls.py
"""
**************************************************************
                        Module / Packages
**************************************************************
"""

"""======  Default  ======"""
from django.urls import path

"""====== Views  ======"""
from Dashboard.views import (
    Dashboard_view,
    Staff_list,
    edit_password,
    reset_password,
    cities_list,
    Add_Cities,
    update_Cities,
    Add_CityAreas,
    Add_CustGrp,
    Add_CustAddress,
    get_cities_for_state,
    get_city_areas_for_city,
    Add_TagMst,
    Add_GroupMst,
    Customer_list,
    add_customers,
    update_customers,
    Customer_Tags,
)

"""
**************************************************************
                        URL Path
**************************************************************
"""

urlpatterns = [
    # ====== set as Default page URL  ======
    path("",Dashboard_view),

    # =============== staff  ===============
    path("Staff_list/",Staff_list,name="Staff_list"),
    path('edit_password/<int:user_id>/', edit_password, name='Edit_Password'),
    path('reset_password/<int:user_id>/', reset_password, name='Reset_Password'),

    # =============== cities  ===============
    path("cities_list/",cities_list,name="cities_list"),
    path("Add_Cities/",Add_Cities,name="Add_Cities"),
    path("update_Cities/<int:id>/",update_Cities,name="update_Cities"),

    # ============= citieAreas  =============
    path("Add_CityAreas/",Add_CityAreas,name="Add_CityAreas"),

    # ============ customerGroup  ============
    path("Add_CustGrp/",Add_CustGrp,name="Add_CustGrp"),

    # ============= CustAddress  =============
    path("Add_CustAddress/",Add_CustAddress,name="Add_CustAddress"),
    path('get_cities_for_state/', get_cities_for_state, name='get_cities'),
    path('get-city-areas/', get_city_areas_for_city, name='get_city_areas'),

    # ================ TagMst  ================
    path('Add_TagMst/', Add_TagMst, name='Add_TagMst'),

    # ================ GroupMst  ================
    path('Add_GroupMst/', Add_GroupMst, name='Add_GroupMst'),

    # ================ CustMst  ================
    path('Customer_list/', Customer_list, name='Customer_list'),
    path('add_customers/', add_customers, name='add_customers'),
    path('update_customer/<int:id>/', update_customers, name='update_customers'),



    path('Customer_Tags', Customer_Tags, name='Customer_Tags'),


    
]

project_FlwUpSys/project_FlwUpSys/urls.py
"""
**************************************************************
                        Module / Packages
**************************************************************
"""
from django.contrib import admin
from django.urls import path , include

"""====== set as Default page module ======"""
from Dashboard.views import (
    Dashboard_view,
)

"""
**************************************************************
                        URL Path
**************************************************************
"""

urlpatterns = [
    # ====== Set as Default page URL  ======
    path('', Dashboard_view, name='homepage'), 

    # ====== App URL  ======
    path('admin/', admin.site.urls),
    path('accounts/',include("accounts.urls")),
    path('Dashboard/', include("Dashboard.urls")),
    path('utils/', include("utils.urls")),
]

project_FlwUpSys/utils/urls.py
"""
**************************************************************
                        Module / Packages
**************************************************************
"""

"""======  Default  ======"""
from django.urls import path , include

"""====== Views  ======"""
from utils.views import (
    CrDetails,
)

"""
**************************************************************
                        URL Path
**************************************************************
"""

urlpatterns = [
    path("Create_Details/",CrDetails,name="Create_Details"),
]

project_FlwUpSys/Dashboard/models.py
from django.db import models
from accounts.user_types import get_DealerTyp


class StateMst(models.Model):
    code = models.CharField(max_length=5, unique=True, blank=False)
    name = models.CharField(max_length=80, unique=True, blank=False)
    isUT = models.BooleanField(default=False)
    Other1 = models.CharField(max_length=60, blank=True)
    Other2 = models.CharField(max_length=60, blank=True)
    CrDtTm = models.DateTimeField(auto_now_add=True)
    CrBy = models.CharField(max_length=60, blank=True)
    CrFrom = models.CharField(max_length=60, blank=True)
    UpdDtTm = models.DateTimeField(auto_now=True)
    UpdBy = models.CharField(max_length=60, blank=True)
    UpdFrom = models.CharField(max_length=60, blank=True)

    def __str__(self):
        return f"{self.name}"

    class Meta:
        db_table = 'StateMst'
        verbose_name = 'StateMst'


class CityMst(models.Model):
    State = models.ForeignKey(StateMst, on_delete=models.RESTRICT)
    Name = models.CharField(max_length=80, blank=False)
    StateCode = models.CharField(max_length=5, default="24", blank=False)
    Other1 = models.CharField(max_length=60, blank=True)
    Other2 = models.CharField(max_length=60, blank=True)
    CrDtTm = models.DateTimeField(auto_now_add=True)
    CrBy = models.CharField(max_length=60, blank=True)
    CrFrom = models.CharField(max_length=60, blank=True)
    UpdDtTm = models.DateTimeField(auto_now=True)
    UpdBy = models.CharField(max_length=60, blank=True)
    UpdFrom = models.CharField(max_length=60, blank=True)

    def __str__(self):
        return f"{self.Name}"

    class Meta:
        db_table = 'CityMst'
        verbose_name = 'CityMst'
        constraints = [
            models.UniqueConstraint(
                fields=['StateCode', 'Name'], name='unq_StateCode_CityName'),
        ]


class CityArea(models.Model):
    City = models. ForeignKey(CityMst, on_delete=models.RESTRICT)
    Name = models.CharField(max_length=80, blank=False)
    Other1 = models.CharField(max_length=60, blank=True)
    Other2 = models.CharField(max_length=60, blank=True)
    CrDtTm = models.DateTimeField(auto_now_add=True)
    CrBy = models.CharField(max_length=60, blank=True)
    CrFrom = models.CharField(max_length=60, blank=True)
    UpdDtTm = models.DateTimeField(auto_now=True)
    UpdBy = models.CharField(max_length=60, blank=True)
    UpdFrom = models.CharField(max_length=60, blank=True)

    def __str__(self):
        return f"{self.Name}"

    class Meta:
        db_table = 'CityArea'
        verbose_name = 'CityArea'
        constraints = [
            models.UniqueConstraint(
                fields=['City', 'Name'], name='unq_CityName_CityArea'),
        ]


class CustGrp(models.Model):
    Code = models.CharField(max_length=5, unique=True, blank=False)
    Name = models.CharField(max_length=5, unique=True, blank=False)
    Other1 = models.CharField(max_length=60, blank=True)
    Other2 = models.CharField(max_length=60, blank=True)
    CrDtTm = models.DateTimeField(auto_now_add=True)
    CrBy = models.CharField(max_length=60, blank=True)
    CrFrom = models.CharField(max_length=60, blank=True)
    UpdDtTm = models.DateTimeField(auto_now=True)
    UpdBy = models.CharField(max_length=60, blank=True)
    UpdFrom = models.CharField(max_length=60, blank=True)

    class Meta:
        db_table = 'CustGrp'
        verbose_name = 'CustGrp'


class CustAddress(models.Model):
    State = models.ForeignKey(StateMst, on_delete=models.RESTRICT)
    City = models. ForeignKey(CityMst, on_delete=models.RESTRICT)
    CityArea = models. ForeignKey(CityArea, on_delete=models.RESTRICT)
    Other1 = models.CharField(max_length=60, blank=True)
    Other2 = models.CharField(max_length=60, blank=True)
    CrDtTm = models.DateTimeField(auto_now_add=True)
    CrBy = models.CharField(max_length=60, blank=True)
    CrFrom = models.CharField(max_length=60, blank=True)
    UpdDtTm = models.DateTimeField(auto_now=True)
    UpdBy = models.CharField(max_length=60, blank=True)
    UpdFrom = models.CharField(max_length=60, blank=True)

    class Meta:
        db_table = 'CustAddress'
        verbose_name = 'CustAddress'


class TagMst(models.Model):
    Code = models.CharField(max_length=5, blank=False, unique=True)
    Name = models.CharField(max_length=80, blank=False, unique=True)
    Other1 = models.CharField(max_length=60, blank=True)
    Other2 = models.CharField(max_length=60, blank=True)
    CrDtTm = models.DateTimeField(auto_now_add=True)
    CrBy = models.CharField(max_length=60, blank=True)
    CrFrom = models.CharField(max_length=60, blank=True)
    UpdDtTm = models.DateTimeField(auto_now=True)
    UpdBy = models.CharField(max_length=60, blank=True)
    UpdFrom = models.CharField(max_length=60, blank=True)

    def __str__(self):
        return f"{self.Code}"

    class Meta:
        db_table = 'TagMst'
        verbose_name = 'TagMst'


class GroupMst(models.Model):
    Code = models.CharField(max_length=5, blank=False, unique=True)
    Name = models.CharField(max_length=80, blank=False, unique=True)
    Other1 = models.CharField(max_length=60, blank=True)
    Other2 = models.CharField(max_length=60, blank=True)
    CrDtTm = models.DateTimeField(auto_now_add=True)
    CrBy = models.CharField(max_length=60, blank=True)
    CrFrom = models.CharField(max_length=60, blank=True)
    UpdDtTm = models.DateTimeField(auto_now=True)
    UpdBy = models.CharField(max_length=60, blank=True)
    UpdFrom = models.CharField(max_length=60, blank=True)

    def __str__(self):
        return f"{self.Code}"

    class Meta:
        db_table = 'GroupMst'
        verbose_name = 'GroupMst'


class CustMst(models.Model):
    Choices = get_DealerTyp()
    Name = models.CharField(max_length=100, blank=False, unique=True)
    GrpMstID = models.ForeignKey(GroupMst, on_delete=models.RESTRICT)
    GrpMstCode = models.CharField(max_length=5, blank=False)
    RespPrsnNm = models.CharField(max_length=80, blank=True)
    RespPrsnMbl = models.CharField(max_length=50, blank=True)
    ContPrsnNm = models.CharField(max_length=80, blank=True)
    ContPrsnMbl = models.CharField(max_length=50, blank=True)
    ContPrsnEMail = models.CharField(max_length=120, blank=True)
    Addr1 = models.CharField(max_length=100, blank=False)
    Addr2 = models.CharField(max_length=100, blank=True)
    Addr3 = models.CharField(max_length=100, blank=True)
    CityAreaID = models.ForeignKey(
        CityArea, on_delete=models.RESTRICT, related_name='custmst_cityarea', blank=False)
    CityMstID = models.ForeignKey(
        CityMst, on_delete=models.RESTRICT, related_name='custmst_citymst', blank=False)
    StateMstID = models.ForeignKey(
        StateMst, on_delete=models.RESTRICT, related_name='custmst_statemst', blank=False)
    StateCode = models.CharField(max_length=5, default=24, blank=False)
    Pincode = models.CharField(max_length=10, blank=True)
    Country = models.CharField(max_length=50, blank=False, default="India")
    Mobile = models.CharField(max_length=50, blank=True)
    Phone = models.CharField(max_length=50, blank=True)
    EMail = models.CharField(max_length=120, blank=True)
    OthContPrsnNm = models.CharField(max_length=80, blank=True)
    OthContPrsnMbl = models.CharField(max_length=50, blank=True)
    OthContPrsnEMail = models.CharField(max_length=120, blank=True)
    OthAddr1 = models.CharField(max_length=100, blank=True)
    OthAddr2 = models.CharField(max_length=100, blank=True)
    OthAddr3 = models.CharField(max_length=100, blank=True)
    OthCityAreaID = models.ForeignKey(
        CityArea, on_delete=models.RESTRICT, related_name='custmst_othcityarea', blank=True, null=True)
    OthCityMstID = models.ForeignKey(
        CityMst, on_delete=models.RESTRICT, related_name='custmst_othcitymst', blank=True, null=True)
    OthStateMstID = models.ForeignKey(
        StateMst, on_delete=models.RESTRICT, related_name='custmst_othstatemst', blank=True, null=True)
    OthStateCode = models.CharField(max_length=5, default=24, blank=True)
    OthPincode = models.CharField(max_length=10, blank=True)
    OthCountry = models.CharField(max_length=50, blank=True)
    OthMobile = models.CharField(max_length=50, blank=True)
    OthPhone = models.CharField(max_length=50, blank=True)
    OthEMail = models.CharField(max_length=120, blank=True)
    WebAddr = models.CharField(max_length=120, blank=True)
    SplRemarks = models.CharField(max_length=200, blank=True)
    DealerTyp = models.CharField(
        max_length=10, choices=Choices, blank=False, default="2")
    GSTNo = models.CharField(max_length=20, blank=True)
    PANNo = models.CharField(max_length=20, blank=True)
    Tags = models.CharField(max_length=50, blank=True)
    Other1 = models.CharField(max_length=60, blank=True)
    Other2 = models.CharField(max_length=60, blank=True)
    CrDtTm = models.DateTimeField(auto_now_add=True)
    CrBy = models.CharField(max_length=60, blank=True)
    CrFrom = models.CharField(max_length=60, blank=True)
    UpdDtTm = models.DateTimeField(auto_now=True)
    UpdBy = models.CharField(max_length=60, blank=True)
    UpdFrom = models.CharField(max_length=60, blank=True)

    def __str__(self):
        return f"{self.Name}"

    class Meta:
        db_table = 'CustMst'
        verbose_name = 'CustMst'


class CustTags(models.Model):
    Tag = models.ForeignKey(TagMst, on_delete=models.RESTRICT)
    Cust = models.ForeignKey(CustMst, on_delete=models.RESTRICT)
    Other1 = models.CharField(max_length=60, blank=True)
    Other2 = models.CharField(max_length=60, blank=True)
    CrDtTm = models.DateTimeField(auto_now_add=True)
    CrBy = models.CharField(max_length=60, blank=True)
    CrFrom = models.CharField(max_length=60, blank=True)
    UpdDtTm = models.DateTimeField(auto_now=True)
    UpdBy = models.CharField(max_length=60, blank=True)
    UpdFrom = models.CharField(max_length=60, blank=True)

    class Meta:
        db_table = 'CustTag'
        verbose_name = 'CustTag'
        constraints = [

project_FlwUpSys/Dashboard/templates/Dashboard/Add_GroupMst.html
{% block head%}
    <style>
        .form-field {
            margin-bottom: 20px; 
          }
    </style>
{% endblock %}
{% block body %}
<h1>Add Customer Groups</h1>
    <form method="post">
        {% csrf_token %}

        <div class="form-field">
            {{ form.Code.label_tag }}
            {{ form.Code }}
            {% if Codeerror_message %}
                <div class="error" style="color:red;">{{ Codeerror_message }}</div>
            {% endif %}
        </div>

        <div class="form-field">
            {{ form.Name.label_tag }}
            {{ form.Name }}
            {% if Nameerror_message %}
                <div class="error" style="color:red;">{{ Nameerror_message }}</div>
            {% endif %}
        </div>

        <div class="form-field">
            {{ form.Other1.label_tag }}
            {{ form.Other1 }}
        </div>

        <div class="form-field">
            {{ form.Other2.label_tag }}
            {{ form.Other2 }}
          </div>
          
          <div class="form-field">
            {{ form.CrDtTm.label_tag }}
            {{ form.CrDtTm }}
          </div>
      
          <div class="form-field">
            {{ form.CrBy.label_tag }}
            {{ form.CrBy }}
          </div>
      
          <div class="form-field">
            {{ form.CrFrom.label_tag }}
            {{ form.CrFrom }}
          </div>
      
          <div class="form-field">
            {{ form.UpdDtTm.label_tag }}
            {{ form.UpdDtTm }}
          </div>
      
          <div class="form-field">
            {{ form.UpdBy.label_tag }}
            {{ form.UpdBy }}
          </div>
      
          <div class="form-field">
            {{ form.UpdFrom.label_tag }}
            {{ form.UpdFrom }}
          </div>

        <button type="submit">Submit</button>
    </form>
{% endblock %}

project_FlwUpSys/Dashboard/templates/Dashboard/Add_TagMst.html
{% block head %}
    <style>
        .form-field {
            margin-bottom: 20px; 
          }
    </style>
{% endblock %}
{% block body %}
<h1>Add Customer Tags</h1>
    <form method="post">
        {% csrf_token %}

        <div class="form-field">
            {{ form.Code.label_tag }}
            {{ form.Code }}
            {% if Codeerror_message %}
                <div class="error" style="color:red;">{{ Codeerror_message }}</div>
            {% endif %}
        </div>

        <div class="form-field">
            {{ form.Name.label_tag }}
            {{ form.Name }}
            {% if Nameerror_message %}
                <div class="error" style="color:red;">{{ Nameerror_message }}</div>
            {% endif %}
        </div>

        <div class="form-field">
            {{ form.Other1.label_tag }}
            {{ form.Other1 }}
        </div>

        <div class="form-field">
            {{ form.Other2.label_tag }}
            {{ form.Other2 }}
          </div>
          
          <div class="form-field">
            {{ form.CrDtTm.label_tag }}
            {{ form.CrDtTm }}
          </div>
      
          <div class="form-field">
            {{ form.CrBy.label_tag }}
            {{ form.CrBy }}
          </div>
      
          <div class="form-field">
            {{ form.CrFrom.label_tag }}
            {{ form.CrFrom }}
          </div>
      
          <div class="form-field">
            {{ form.UpdDtTm.label_tag }}
            {{ form.UpdDtTm }}
          </div>
      
          <div class="form-field">
            {{ form.UpdBy.label_tag }}
            {{ form.UpdBy }}
          </div>
      
          <div class="form-field">
            {{ form.UpdFrom.label_tag }}
            {{ form.UpdFrom }}
          </div>

        <button type="submit">Submit</button>
    </form>
{% endblock %}

project_FlwUpSys/Dashboard/templates/Dashboard/Add_cityArea.html
<h1>Add City Areas</h1>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Submit</button>
    </form>

project_FlwUpSys/Dashboard/templates/Dashboard/Add_custAddress.html
{% block head %}
<style>
  .form-field {
    margin-bottom: 20px; 
  }
</style>
{% endblock %}

{% block body %}
  <h1>Add Customer Address</h1>
  <form method="post" id="address-form">
    {% csrf_token %}
    
    <div class="form-field">
      {{ form.State.label_tag }}
      {{ form.State }}
    </div>

    <div class="form-field">
      {{ form.City.label_tag }}
      {{ form.City }}
      <div id="add-city-container" style="display:inline;">
        <button id="AddCity">Add City</button>
      </div>
    </div>

    <div class="form-field">
      {{ form.CityArea.label_tag }}
      {{ form.CityArea }}
      <div id="add-cityArea-container" style="display:inline;">
        <button id="AddCityArea">Add CityArea</button>
      </div>    
    </div>

    <div class="form-field">
      {{ form.Other1.label_tag }}
      {{ form.Other1 }}
    </div>

    <div class="form-field">
      {{ form.Other2.label_tag }}
      {{ form.Other2 }}
    </div>
    
    <div class="form-field">
      {{ form.CrDtTm.label_tag }}
      {{ form.CrDtTm }}
    </div>

    <div class="form-field">
      {{ form.CrBy.label_tag }}
      {{ form.CrBy }}
    </div>

    <div class="form-field">
      {{ form.CrFrom.label_tag }}
      {{ form.CrFrom }}
    </div>

    <div class="form-field">
      {{ form.UpdDtTm.label_tag }}
      {{ form.UpdDtTm }}
    </div>

    <div class="form-field">
      {{ form.UpdBy.label_tag }}
      {{ form.UpdBy }}
    </div>

    <div class="form-field">
      {{ form.UpdFrom.label_tag }}
      {{ form.UpdFrom }}
    </div>

    <button type="submit">Add Address</button>

  </form>
  <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>

  <script>
    $(document).ready(function() {
      var citySelect = $('#id_City');
      var cityAreaSelect = $('#id_CityArea');
    
    $('#id_State').change(function() {
      var selectedState = $(this).val();
      citySelect.empty();
      cityAreaSelect.empty();

      if (selectedState) {
        $.get('{% url 'get_cities' %}', { state_name: selectedState }, function(data) {
          if (data.cities.length === 0) {
            citySelect.append($('<option>', {
              value: '',
              text: 'None'
            }));
            addCityContainer.show(); // Show the "Add City" button
          } else {
            $.each(data.cities, function(index, city) {
              citySelect.append($('<option>', {
                value: city.Name,
                text: city.Name
              }));
            });
            addCityContainer.hide(); // Hide the "Add City" button
          }
          citySelect.trigger('change');
        });
      }
    });

    citySelect.change(function() {
      var selectedCity = $(this).val();
      cityAreaSelect.empty();
      addCityAreaContainer.empty();

      if (!selectedCity) {
        cityAreaSelect.append($('<option>', {
          value: '',
          text: 'None'
        }));
        addCityAreaContainer.show(); // Show the "Add CityArea" button

        var addCityAreaButton = $('<button>', {
          id: 'AddCityArea',
          text: 'Add CityArea'
        });

        addCityAreaButton.on('click', function() {
          window.location.href = '{% url 'Add_CityAreas' %}';
        });

        
      } else {
        $.get('{% url 'get_city_areas' %}', { city_name: selectedCity }, function(data) {
          if (data.city_areas.length === 0) {
            cityAreaSelect.append($('<option>', {
              value: '',
              text: 'None'
            }));
            addCityAreaContainer.show(); // Show the "Add CityArea" button

            var addCityAreaButton = $('<button>', {
              id: 'AddCityArea',
              text: 'Add CityArea'
            });

            addCityAreaButton.on('click', function() {
              window.location.href = '{% url 'Add_CityAreas' %}';
            });

            
          } else {
            $.each(data.city_areas, function(index, cityArea) {
              cityAreaSelect.append($('<option>', {
                value: cityArea.Name,
                text: cityArea.Name
              }));
            });
            
          }
        });
      }
    });

    $('#AddCity').on('click', function() {
      // Redirect to a new HTML form or URL
      window.location.href = '{% url 'Add_Cities' %}';
    });
  });

  </script>
{% endblock %}

project_FlwUpSys/Dashboard/templates/Dashboard/Add_custgrp.html
<h2>Add Customer Group</h2>
<form method="post">
  {% csrf_token %}
  {{ form.as_p }}
  <button type="submit">Add Group</button>
</form>

project_FlwUpSys/Dashboard/templates/Dashboard/edit_password.html
<h1>Edit Password</h1>
<form method="post">
    {% csrf_token %}
    {{ password_form.as_p }}
    <button type="submit">Save Password</button>
</form>

project_FlwUpSys/Dashboard/templates/Dashboard/homepage.html
<!doctype html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta http-equiv="Content-Language" content="en">
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <title>FollowUpSystem</title>
    <meta name="viewport"content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no, shrink-to-fit=no" />
    <meta name="description" content="This is an example dashboard created using build-in elements and components.">
    <meta name="msapplication-tap-highlight" content="no">
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/home.css' %}">
</head>

<body>
    <div class="app-container app-theme-white body-tabs-shadow fixed-header fixed-sidebar">
        {% comment %} ==================== Header Logo & hamburger ====================   {% endcomment %}
        {% include 'Dashboard/header.html' %}
        
        {% comment %} ======================== sidebar ========================== {% endcomment %}
        <div class="app-main">
            {% include 'Dashboard/sidebar.html' %}
        </div>
    </div>   
    <script src="{% static 'js/home.js' %}"></script>
</body>

</html>

project_FlwUpSys/Dashboard/templates/Dashboard/sidebar.html
    <div class="app-sidebar sidebar-shadow" >
        <div class="app-header__logo">
            <div class="logo-src"></div>
            <div class="header__pane ml-auto" >
                <div>
                    <button type="button" class="hamburger close-sidebar-btn hamburger--elastic" data-class="closed-sidebar">
                    <span class="hamburger-box">
                        <span class="hamburger-inner"></span>
                        </span>
                    </button>
                </div>
            </div>
        </div>
        <div class="app-header__mobile-menu" >
            <div>
                <button type="button" class="hamburger hamburger--elastic mobile-toggle-nav">
                    <span class="hamburger-box">
                        <span class="hamburger-inner"></span>
                    </span>
                </button>
            </div>
        </div>
        <div class="app-header__menu">
            <span>
                <button type="button" class="btn-icon btn-icon-only btn btn-primary btn-sm mobile-toggle-header-nav">
                    <span class="btn-icon-wrapper">
                        <i class="fa fa-ellipsis-v fa-w-6"></i>
                    </span>
                </button>
            </span>
        </div>
        <div class="scrollbar-sidebar">
            <div class="app-sidebar__inner">
                <ul class="vertical-nav-menu">
                    <li class="app-sidebar__heading">Menu</li>
                        <li class="mm-active">
                            <a href="/">Dashboard</a>
                        </li>
                        <li class="app-sidebar__heading">Master</li>
                        {% if user.is_superuser %}
                            <li class="mm-active">
                                <a href="{% url 'Staff_list' %}">Staff</a>
                            </li>
                        {% endif %}
                        <li class="mm-active">
                            <a href="{% url 'cities_list' %}">Cities</a>
                        </li>
                        {% comment %} <li class="mm-active">
                            <a href="{% url 'Add_CityAreas' %}">CityArea</a>
                        </li> {% endcomment %}
                        {% comment %} <li class="mm-active">
                            <a href="{% url 'Add_CustGrp' %}">Custgrp</a>
                        </li>
                        <li class="mm-active">
                            <a href="{% url 'Add_CustAddress' %}">CustAddress</a>
                        </li>
                        <li class="mm-active">
                            <a href="{% url 'Add_TagMst' %}">TagMst</a>
                        </li>
                        <li class="mm-active">
                            <a href="{% url 'Add_GroupMst' %}">GroupMst</a>
                        </li> {% endcomment %}
                        <li class="mm-active">
                            <a href="{% url 'Customer_list' %}">Customer</a>
                        </li>
                        <li class="mm-active">
                            <a href="{% url 'Customer_Tags' %}">Customer Tags</a>
                        </li>
                    <li class="app-sidebar__heading">Transction</li>
                    <li class="app-sidebar__heading">Reports</li>
                </ul>
            </div>
        </div>
    </div>

    